import type { Metadata } from "next";
import { GeistSans, GeistMono } from 'geist/font'
import { ClerkProvider } from '@clerk/nextjs';
import { Providers } from "@/components/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans antialiased`}>
          <Providers>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              {/* Header content */}
            </header>
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}